description = "ubi 8 base image with no buildpacks included. To use, specify buildpacks at build time."

[lifecycle]
  version = "0.18.5"

[stack]
  build-image = "docker.io/paketocommunity/build-ubi-base:0.0.39"
  id = "io.buildpacks.stacks.ubi8"
  run-image = "index.docker.io/paketocommunity/run-ubi-base:latest"
  run-image-mirrors = []
