description = "ubi 8 builder with no buildpacks included. To use, specify buildpacks at build time."

[build]
  image = "docker.io/paketobuildpacks/build-ubi8-base:0.0.274"

[lifecycle]
  version = "0.21.18"

[run]

  [[run.images]]
    image = "docker.io/paketobuildpacks/run-ubi8-base:latest"

[[targets]]
  arch = "amd64"
  os = "linux"

[[targets]]
  arch = "arm64"
  os = "linux"

[[targets]]
  arch = "ppc64le"
  os = "linux"

[[targets]]
  arch = "s390x"
  os = "linux"
