description = "ubi 8 base image with no buildpacks included. To use, specify buildpacks at build time."

[lifecycle]
  version = "0.20.6"

[stack]
  build-image = "docker.io/paketobuildpacks/build-ubi8-base:0.0.103"
  id = "io.buildpacks.stacks.ubi8"
  run-image = "index.docker.io/paketobuildpacks/run-ubi8-base:latest"
  run-image-mirrors = []
